### ISSUE TITLE
"map" function was deprecated in Terraform v0.12 and is no longer available

### ISSUE THREAD

**Issue by tomart** [aws-samples/terraform-aws-sap-netweaver-on-hana#1]
Hello,

when calling terraform validate the following errors occur:

Error: Error in function call
│
│   on modules\aws-sap-app-host\ebs.tf line 32, in resource "aws_ebs_volume" "xvdf_volume":
│   32:   map("Name", "${module.tags.values["Name"]}-app_usr_sap"))
│     ├────────────────
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-app-host\ebs.tf line 55, in resource "aws_ebs_volume" "xvdg_volume":
│   55:   map("Name", "${module.tags.values["Name"]}-app_swap"))
│     ├────────────────
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-ascs-host\ebs.tf line 31, in resource "aws_ebs_volume" "xvdg_volume":
│   31:   map("Name", "${module.tags.values["Name"]}-ascs_swap"))
│     ├────────────────
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-ascs-host\ebs.tf line 52, in resource "aws_ebs_volume" "xvdf_volume":
│   52:   map("Name", "${module.tags.values["Name"]}-ascs_usr_sap"))
│     ├────────────────
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-ascs-host\ebs.tf line 75, in resource "aws_ebs_volume" "xvdh_volume":
│   75:   map("Name", "${module.tags.values["Name"]}-app_sapmnt"))
│     ├────────────────
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-hana-host\ebs.tf line 57, in resource "aws_ebs_volume" "xvdo_volume":
│   57:   map("Name", "${module.tags.values["Name"]}-hana_shared"))
│     ├────────────────
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-hana-host\ebs.tf line 80, in resource "aws_ebs_volume" "data_volumes":
│   80:   map("Name", "${module.tags.values["Name"]}-hana_data-${count.index}"))
│     ├────────────────
│     │ count.index is a number, known only after apply
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-hana-host\ebs.tf line 104, in resource "aws_ebs_volume" "log_volumes":
│  104:   map("Name", "${module.tags.values["Name"]}-hana_log-${count.index}"))
│     ├────────────────
│     │ count.index is a number, known only after apply
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-hana-host\ebs.tf line 129, in resource "aws_ebs_volume" "backup_volumes":
│  129:   map("Name", "${module.tags.values["Name"]}-hana_backup"))
│     ├────────────────
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-hana-host\ebs.tf line 152, in resource "aws_ebs_volume" "usr_sap_volumes":
│  152:   map("Name", "${module.tags.values["Name"]}-hana_usr_sap"))
│     ├────────────────
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.
╵
╷
│ Error: Error in function call
│
│   on modules\aws-sap-hana-host\ebs.tf line 176, in resource "aws_ebs_volume" "xvdr_volume":
│  176:   map("Name", "${module.tags.values["Name"]}-app_swap"))
│     ├────────────────
│     │ module.tags.values["Name"] will be known only after apply
│
│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use
│ tomap({ ... }) syntax to write a literal map.

What is not correct?

Regards
Thomas

**Comment by mendonca-glenn** [comment]
Hi Thomas, thank you for reporting the issue. I have updated the code base to replace the map functions with tomap. I have tested latest commit with Terraform v0.15.0 and didn't run into the issue you reported. Kindly pull the latest commit and let me know if you still observe any issues.

Thanks,
Glenn

**Comment by tomart** [comment]
Hello Genn,

thank you for providing this fix so fast!

"terraform validate" reports no errors now.

Regards
Thomas

**Comment by mendonca-glenn** [comment]
Thank you Thomas for confirming!
