### ISSUE TITLE
Still issues with map function

### ISSUE THREAD

**Issue by tomart** [aws-samples/terraform-aws-sap-netweaver-on-hana#2]
Hello Glenn,
 
unfornately there are still issues after cloning the actual version of terraform-aws-sap-netweaver-on-hana.
 
I decided to start with the sap_hana_simple_example.
 
First I adapted the file terraform.tfvars - file with the values of our AWS subscription.
 
Then I ran the following commands in the sap_hana_simple_example-Folder:
 
terraform init
terraform plan -out=s1.tfplan
 
But these errors occured:
 

Error: Error in function call

│

│   on ..\..\modules\aws-sap-hana-host\ebs.tf line 57, in resource "aws_ebs_volume" "xvdo_volume":

│   57:   map("Name", "${module.tags.values["Name"]}-hana_shared"))

│     ├────────────────

│     │ module.tags.values["Name"] will be known only after apply

│

│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use tomap({ ... }) syntax to write a literal map.

╵

╷

│ Error: Error in function call

│

│   on ..\..\modules\aws-sap-hana-host\ebs.tf line 80, in resource "aws_ebs_volume" "data_volumes":

│   80:   map("Name", "${module.tags.values["Name"]}-hana_data-${count.index}"))

│     ├────────────────

│     │ count.index is a number, known only after apply

│     │ module.tags.values["Name"] will be known only after apply

│

│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use tomap({ ... }) syntax to write a literal map.

╵

╷

│ Error: Error in function call

│

│   on ..\..\modules\aws-sap-hana-host\ebs.tf line 104, in resource "aws_ebs_volume" "log_volumes":

│  104:   map("Name", "${module.tags.values["Name"]}-hana_log-${count.index}"))

│     ├────────────────

│     │ count.index is a number, known only after apply

│     │ module.tags.values["Name"] will be known only after apply

│

│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use tomap({ ... }) syntax to write a literal map.

╵

╷

│ Error: Error in function call

│

│   on ..\..\modules\aws-sap-hana-host\ebs.tf line 129, in resource "aws_ebs_volume" "backup_volumes":

│  129:   map("Name", "${module.tags.values["Name"]}-hana_backup"))

│     ├────────────────

│     │ module.tags.values["Name"] will be known only after apply

│

│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use tomap({ ... }) syntax to write a literal map.

╵

╷

│ Error: Error in function call

│

│   on ..\..\modules\aws-sap-hana-host\ebs.tf line 152, in resource "aws_ebs_volume" "usr_sap_volumes":

│  152:   map("Name", "${module.tags.values["Name"]}-hana_usr_sap"))

│     ├────────────────

│     │ module.tags.values["Name"] will be known only after apply

│

│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use tomap({ ... }) syntax to write a literal map.

╵

╷

│ Error: Error in function call

│

│   on ..\..\modules\aws-sap-hana-host\ebs.tf line 176, in resource "aws_ebs_volume" "xvdr_volume":

│  176:   map("Name", "${module.tags.values["Name"]}-app_swap"))

│     ├────────────────

│     │ module.tags.values["Name"] will be known only after apply

│

│ Call to function "map" failed: the "map" function was deprecated in Terraform v0.12 and is no longer available; use tomap({ ... }) syntax to write a literal map.

╵

 

What went wrong?

 

Regards

Thomas

**Comment by mendonca-glenn** [comment]
Thank you for reaching out Thomas. Kindly pull the latest changes, and retry! Not sure what went wrong - looking into that at the moment. I performed a new commit and the changes are now live.  As before appreciate the feedback.

Thanks,
Glenn

**Comment by tomart** [comment]
Hello Glenn.

it is working now! We are able to deploy!

Thank you very much!

Regards
Thomas
